package Propuesta_de_ejercicio_02;
import java.sql.*;
import java.util.ArrayList;
import java.util.List;

public class ConnectDB {
	protected final String BBDD;
	protected final String USER;
	protected final String PASSWORD;
	
	//Constructor por defecto
	public ConnectDB() {
		BBDD = "jdbc:oracle:thin:@localhost:1521:xe";
		USER = "Denji2024";
		PASSWORD = "TuContrasena";
	}
	
	public ConnectDB(String BBDD, String USER, String PASSWORD) {
		this.BBDD = BBDD;
		this.USER = USER;
		this.PASSWORD = PASSWORD;
	}
	
	public void connectToDB() throws SQLException {
	    Connection connect = DriverManager.getConnection(BBDD, USER, PASSWORD);
	    Statement sentencia = connect.createStatement();

	    // No es necesario eliminar el esquema si planeas crearlo después

	    // Usamos el nuevo esquema
	    String use = "use m06_1s22230"; // Esta línea no es válida en Oracle SQL, omitir

	    // Creamos una tabla
	    String crearTabla = "CREATE TABLE Alumno (id_alumno INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, nombre varchar(50) NOT NULL)";
	    sentencia.executeUpdate(crearTabla);

	    // Insertamos valores en la tabla
	    String insert = "INSERT INTO Alumno (nombre) VALUES ('Álvaro')";
	    sentencia.executeUpdate(insert);

	    insert = "INSERT INTO Alumno (nombre) VALUES ('Pedro')";
	    sentencia.executeUpdate(insert);

	    insert = "INSERT INTO Alumno (nombre) VALUES ('María')";
	    sentencia.executeUpdate(insert);

	    insert = "INSERT INTO Alumno (nombre) VALUES ('Paula')";
	    sentencia.executeUpdate(insert);

	    // Hacemos una consulta en la BD
	    ResultSet result = sentencia.executeQuery("SELECT * FROM Alumno");
	    List<Alumno> alumnoList = new ArrayList<>();
	    while (result.next()) {
	        Alumno alumno = new Alumno(result.getLong("id_alumno"), result.getString("nombre"));
	        alumnoList.add(alumno); // Guardamos alumno en una lista
	    }

	    System.out.println("Mostrar alumnoList.toString: \n");
	    System.out.println(alumnoList.toString()); // Imprimimos la lista por consola
	    System.out.println();

	    // Primera aproximación para mostrar al usuario
	    System.out.println("Mostrar alumnoList alumno a alumno: \n");
	    for (Alumno alum : alumnoList) {
	        System.out.println(alum.toString());
	    }
	    result.close();
	    sentencia.close();
	    connect.close();
	}
}